### Send POST request with json body
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "owner": "vasa",
  "currency": "USD"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send GET request with json body
GET http://localhost:8080/accounts/1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send GET request with json body
GET http://localhost:8080/accounts?page_id=1&page_size=5
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "from_account_id": 44,
  "to_account_id": 43,
  "amount": 10,
  "currency": "CAD"
}

### Send POST request with json body
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "vasa",
  "password": "secret",
  "full_name": "Vasiliy",
  "email": "v@i.ua"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}