### Send POST request with json body
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "owner": "vasa",
  "currency": "USD"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send GET request with json body
GET http://localhost:8080/accounts/1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send GET request with json body
GET http://localhost:8080/accounts?page_id=1&page_size=5
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "from_account_id": 44,
  "to_account_id": 43,
  "amount": 10,
  "currency": "CAD"
}

### Send POST request with json body
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "vasa",
  "password": "secret",
  "full_name": "Vasiliy",
  "email": "v@i.ua"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/v1/create_user
Content-Type: application/json

{
  "username": "ivan",
  "password": "secret",
  "full_name": "Ivan",
  "email": "i@i.ua"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/v1/create_user
Content-Type: application/json

{
  "username": "ivan??",
  "password": "secret???",
  "full_name": "12312",
  "email": "ii.ua"
}

> {%
client.test("Bad request", function() {
  client.assert(response.status === 400, "Response status is not 200");
});
%}

### Send PATCH request with json body
PATCH http://localhost:8080/v1/update_user
Content-Type: application/json

{
  "username": "ivan",
  "password": "11111111"
}

> {%
client.test("Bad request", function() {
  client.assert(response.status === 400, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/v1/login_user
Content-Type: application/json

{
  "username": "ivan",
  "password": "secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "vasa",
  "password": "secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Send POST request with json body
POST http://localhost:8080/tokens/renew_access
Content-Type: application/json

{
  "refresh_token": "v2.local.wDImDQIDg0UIO1Z7r9I_iROX0-9U675fP9jRBNLDZGLsfduvtQ8niIDcU3YXK8GirZkL8lLI_B6MR1LPHQO85i-X2L6XIIdN6qEzlqcQuUzaUyyD9W_lqoauyDASOvulC8nEsDCjWbqJppaoIESpRv1l_xm1d-5mRc1F-d39UdOfaLvU3TpuxCQt9I_vUIpTycnYBLK6slbGQqgLR4Q6MUNQsvKV3PF1ipXtm1KlxkD3jMM8FFOhRPqLXLORJc5pxS_0piCX.bnVsbA"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}